import { FlightResult } from '../types';
import { AIRPORTS } from './airports';

const findAirport = (code: string) => {
  const airport = AIRPORTS.find(a => a.code === code);
  if (!airport) throw new Error(`Airport ${code} not found`);
  return airport;
};

export const MOCK_FLIGHT_RESULTS: FlightResult[] = [
  {
    id: 'FL-001',
    airline: 'United Airlines',
    airlineCode: 'UA',
    flightNumber: 'UA 2451',
    origin: findAirport('JFK'),
    destination: findAirport('LAX'),
    departureTime: '06:15 AM',
    arrivalTime: '09:38 AM',
    duration: '5h 23m',
    stops: 0,
    stopCities: [],
    price: 247,
    originalPrice: 312,
    seatsLeft: 4,
    aircraft: 'Boeing 737-900',
    cabinClass: 'economy',
    amenities: ['Wi-Fi', 'Power outlets', 'Entertainment'],
    co2Emissions: '189 kg CO₂',
    baggageIncluded: false,
    refundable: false,
  },
  {
    id: 'FL-002',
    airline: 'Delta Air Lines',
    airlineCode: 'DL',
    flightNumber: 'DL 1087',
    origin: findAirport('JFK'),
    destination: findAirport('LAX'),
    departureTime: '08:30 AM',
    arrivalTime: '11:55 AM',
    duration: '5h 25m',
    stops: 0,
    stopCities: [],
    price: 289,
    originalPrice: 289,
    seatsLeft: 12,
    aircraft: 'Airbus A321neo',
    cabinClass: 'economy',
    amenities: ['Wi-Fi', 'Power outlets', 'Entertainment', 'Snacks'],
    co2Emissions: '175 kg CO₂',
    baggageIncluded: true,
    refundable: false,
  },
  {
    id: 'FL-003',
    airline: 'American Airlines',
    airlineCode: 'AA',
    flightNumber: 'AA 119',
    origin: findAirport('JFK'),
    destination: findAirport('LAX'),
    departureTime: '10:00 AM',
    arrivalTime: '02:10 PM',
    duration: '6h 10m',
    stops: 1,
    stopCities: ['Dallas (DFW)'],
    price: 198,
    originalPrice: 265,
    seatsLeft: 8,
    aircraft: 'Boeing 787-9',
    cabinClass: 'economy',
    amenities: ['Wi-Fi', 'Entertainment'],
    co2Emissions: '210 kg CO₂',
    baggageIncluded: false,
    refundable: false,
  },
  {
    id: 'FL-004',
    airline: 'JetBlue',
    airlineCode: 'B6',
    flightNumber: 'B6 523',
    origin: findAirport('JFK'),
    destination: findAirport('LAX'),
    departureTime: '12:45 PM',
    arrivalTime: '04:02 PM',
    duration: '5h 17m',
    stops: 0,
    stopCities: [],
    price: 219,
    originalPrice: 219,
    seatsLeft: 15,
    aircraft: 'Airbus A321',
    cabinClass: 'economy',
    amenities: ['Wi-Fi', 'Live TV', 'Snacks', 'Extra legroom'],
    co2Emissions: '182 kg CO₂',
    baggageIncluded: true,
    refundable: true,
  },
  {
    id: 'FL-005',
    airline: 'Spirit Airlines',
    airlineCode: 'NK',
    flightNumber: 'NK 2174',
    origin: findAirport('JFK'),
    destination: findAirport('LAX'),
    departureTime: '03:20 PM',
    arrivalTime: '08:45 PM',
    duration: '7h 25m',
    stops: 1,
    stopCities: ['Fort Lauderdale (FLL)'],
    price: 127,
    originalPrice: 159,
    seatsLeft: 2,
    aircraft: 'Airbus A320neo',
    cabinClass: 'economy',
    amenities: [],
    co2Emissions: '245 kg CO₂',
    baggageIncluded: false,
    refundable: false,
  },
  {
    id: 'FL-006',
    airline: 'Alaska Airlines',
    airlineCode: 'AS',
    flightNumber: 'AS 1267',
    origin: findAirport('JFK'),
    destination: findAirport('LAX'),
    departureTime: '05:50 PM',
    arrivalTime: '09:12 PM',
    duration: '5h 22m',
    stops: 0,
    stopCities: [],
    price: 263,
    originalPrice: 315,
    seatsLeft: 6,
    aircraft: 'Boeing 737 MAX 9',
    cabinClass: 'economy',
    amenities: ['Wi-Fi', 'Power outlets', 'Entertainment', 'Free messaging'],
    co2Emissions: '171 kg CO₂',
    baggageIncluded: true,
    refundable: false,
  },
  {
    id: 'FL-007',
    airline: 'United Airlines',
    airlineCode: 'UA',
    flightNumber: 'UA 839',
    origin: findAirport('JFK'),
    destination: findAirport('LAX'),
    departureTime: '09:15 PM',
    arrivalTime: '12:40 AM',
    duration: '5h 25m',
    stops: 0,
    stopCities: [],
    price: 204,
    originalPrice: 204,
    seatsLeft: 20,
    aircraft: 'Boeing 777-200',
    cabinClass: 'economy',
    amenities: ['Wi-Fi', 'Power outlets', 'Entertainment', 'Meal'],
    co2Emissions: '195 kg CO₂',
    baggageIncluded: false,
    refundable: true,
  },
  {
    id: 'FL-008',
    airline: 'Delta Air Lines',
    airlineCode: 'DL',
    flightNumber: 'DL 478',
    origin: findAirport('JFK'),
    destination: findAirport('LAX'),
    departureTime: '11:30 PM',
    arrivalTime: '05:15 AM',
    duration: '7h 45m',
    stops: 1,
    stopCities: ['Minneapolis (MSP)'],
    price: 178,
    originalPrice: 234,
    seatsLeft: 9,
    aircraft: 'Boeing 757-200',
    cabinClass: 'economy',
    amenities: ['Wi-Fi', 'Entertainment'],
    co2Emissions: '228 kg CO₂',
    baggageIncluded: false,
    refundable: false,
  },
];
